export { DashboardPage } from './DashboardPage'
export { HomePage } from './HomePage'
export { LoginPage } from './LoginPage'
export { ResultPage } from './ResultPage'
export { StartEvaluationPage } from './StartEvaluationPage'
